<#
  gen-enums.ps1 â€” re-reference/enums.csv  ->  op2/abi/enums.hpp
  Emits each engine enum as enum class/enum with faithful values (explicit kept, expressions kept verbatim,
  auto left implicit so C++ reproduces the engine's auto-increment). Anonymous enums -> constexpr ints.
  Re-runnable.  Usage: powershell -File gen-enums.ps1 [-Ref <dir>] [-Out <dir>]
#>
param([string]$Ref="$PSScriptRoot\..\..\re-reference", [string]$Out="$PSScriptRoot\..\include\op2\abi")
$ErrorActionPreference='Stop'
if(-not(Test-Path $Out)){ New-Item -ItemType Directory -Path $Out -Force | Out-Null }
function San([string]$s){ $s=[regex]::Replace($s,'[^A-Za-z0-9_]','_'); if($s -eq ''){ $s='_' }; if($s -match '^[0-9]'){ $s='_'+$s }; return $s }
$map = @{ 'uint8'='std::uint8_t';'uint16'='std::uint16_t';'uint32'='std::uint32_t';'uint64'='std::uint64_t';'int8'='std::int8_t';'int16'='std::int16_t';'int32'='std::int32_t';'int64'='std::int64_t';'int'='int';'char'='char';'bool'='bool' }

$rows = Import-Csv -LiteralPath (Join-Path $Ref 'enums.csv')
$order = New-Object System.Collections.Generic.List[string]; $seen=@{}
foreach($r in $rows){ if(-not $seen.ContainsKey($r.enum)){ $seen[$r.enum]=$true; $order.Add($r.enum) } }

# --- Order enums so any enum referenced in another's value expression is emitted FIRST (e.g. OreType
#     before MineType, whose values are int(OreType::...)). DFS topo sort; first-appearance order as tiebreak. ---
$enumNames = @{}; foreach($r in $rows){ if($r.enum -ne ''){ $enumNames[$r.enum] = $true } }
$script:deps = @{}
foreach($en in $order){
  $refs = @{}
  if($en -ne ''){
    foreach($r in ($rows | Where-Object { $_.enum -eq $en })){
      if($r.value_expr){
        foreach($m in [regex]::Matches($r.value_expr, '([A-Za-z_]\w*)::')){
          $ref = $m.Groups[1].Value
          if($enumNames.ContainsKey($ref) -and ($ref -ne $en)){ $refs[$ref] = $true }
        }
      }
    }
  }
  $script:deps[$en] = @($refs.Keys)
}
$script:emitted = @{}
$script:emitOrder = New-Object System.Collections.Generic.List[string]
function Visit-Enum([string]$en) {
  if($script:emitted.ContainsKey($en)){ return }
  $script:emitted[$en] = $true                          # mark before recursing (cycle guard)
  foreach($d in $script:deps[$en]){ Visit-Enum $d }
  $script:emitOrder.Add($en)                             # post-order => dependencies first
}
foreach($en in $order){ Visit-Enum $en }

$L = New-Object System.Collections.Generic.List[string]
$L.Add('// AUTO-GENERATED by tools/gen-enums.ps1 from re-reference/enums.csv -- do not edit by hand.')
$L.Add('// Outpost2.exe enum definitions (values are facts about the binary); see re-reference/RE-REFERENCE.md.')
$L.Add('// NOTE: a few enumerators with expression values may reference engine constants; review if they fail.')
$L.Add('// Unscoped engine enums (e.g. MapID) are isolated in a <Name>Impl sub-namespace and re-exported via')
$L.Add('// `using` so their enumerators do not leak/collide in op2::abi. Access as op2::abi::<Name>::<Enumerator>.')
$L.Add('#pragma once')
$L.Add('#include <cstdint>')
$L.Add('')
$L.Add('namespace op2::abi {')
$L.Add('')

$enumCount=0; $anonCount=0; $valCount=0
foreach($en in $emitOrder){
  $er = @($rows | Where-Object { $_.enum -eq $en })
  if($er.Count -eq 0){ continue }
  $firstFile = $er[0].file
  $er = @($er | Where-Object { $_.file -eq $firstFile })

  if($en -eq ''){
    $L.Add('// (anonymous enum from ' + $firstFile + ')')
    foreach($r in $er){
      $v=''
      if($r.value_expr){ $v=$r.value_expr } elseif($r.value_dec -ne ''){ $v=$r.value_dec }
      if($v -ne ''){ $L.Add(("inline constexpr int {0} = {1};" -f (San $r.enumerator), $v)); $valCount++ }
    }
    $L.Add(''); $anonCount++; continue
  }

  $scoped = ($er[0].scoped -eq 'True')
  $ut = $er[0].underlying
  $cpput=''
  if($ut -ne ''){ if($map.ContainsKey($ut)){ $cpput=$map[$ut] } else { $cpput=$ut } }
  $name = San $en
  $utClause = ''
  if($cpput -ne ''){ $utClause = ' : ' + $cpput }
  if($scoped){
    # scoped enum (enum class): enumerators are already isolated -> emit directly
    $L.Add('enum class ' + $name + $utClause + ' {')
    $close = '};'
  } else {
    # UNSCOPED enum: isolate its enumerators in a <Name>Impl sub-namespace so they do not leak into
    # op2::abi and collide across enums (e.g. multiple None/Count). Mirrors TethysAPI's MapIDImpl pattern;
    # the type is re-exported via `using`, so callers still write op2::abi::<Name>::<Enumerator>.
    $L.Add('namespace ' + $name + 'Impl { enum ' + $name + $utClause + ' {')
    $close = '}; }'
  }
  $seenEnum = @{}; $dropped = 0
  foreach($r in $er){
    $nm = $r.enumerator
    if($seenEnum.ContainsKey($nm)){ $dropped++; continue }   # drop dup enumerator (same-named enums merged)
    $seenEnum[$nm] = $true
    if($r.value_expr){ $L.Add("  $nm = $($r.value_expr),") }
    elseif($r.kind -eq 'explicit'){ $L.Add("  $nm = $($r.value_dec),") }
    else { $L.Add("  $nm,") }
    $valCount++
  }
  if($dropped -gt 0){ $L.Add("  // NOTE: $dropped duplicate enumerator(s) dropped (a same-named enum from another namespace was merged; values here are the first definition's)") }
  $L.Add($close)
  if(-not $scoped){ $L.Add('using ' + $name + ' = ' + $name + 'Impl::' + $name + ';') }
  $L.Add('')
  $enumCount++
}
$L.Add('} // namespace op2::abi')
[IO.File]::WriteAllText((Join-Path $Out 'enums.hpp'), ($L -join "`r`n") + "`r`n", (New-Object Text.UTF8Encoding($false)))
"enums.hpp written: $enumCount enums (+$anonCount anonymous), $valCount enumerators."
