<#
  gen-command-map.ps1 â€” re-reference/command-map.csv  ->  op2/abi/command_map.hpp
  Maps each abi::CommandType to its command-packet payload struct (abi::raw::*), the analogue of
  TethysAPI's CmdPacketDataFor. Requires the command-packet structs to be defined (complete them from
  structs.scaffold.hpp). Re-runnable.  Usage: powershell -File gen-command-map.ps1 [-Ref <dir>] [-Out <dir>]
#>
param([string]$Ref="$PSScriptRoot\..\..\re-reference", [string]$Out="$PSScriptRoot\..\include\op2\abi")
$ErrorActionPreference='Stop'
if(-not(Test-Path $Out)){ New-Item -ItemType Directory -Path $Out -Force | Out-Null }
function San([string]$s){ $s=[regex]::Replace($s,'[^A-Za-z0-9_]','_'); if($s -eq ''){ $s='_' }; if($s -match '^[0-9]'){ $s='_'+$s }; return $s }

$rows = Import-Csv -LiteralPath (Join-Path $Ref 'command-map.csv')
$L = New-Object System.Collections.Generic.List[string]
$L.Add('// AUTO-GENERATED by tools/gen-command-map.ps1 from re-reference/command-map.csv -- do not edit by hand.')
$L.Add('// Maps abi::CommandType -> its command-packet payload struct (abi::raw::*).')
$L.Add('#pragma once')
$L.Add('#include "op2/abi/enums.hpp"        // CommandType')
$L.Add('#include "op2/abi/raw/command.hpp"  // the raw::* payload structs this table names')
$L.Add('')
$L.Add('namespace op2::abi {')
$L.Add('')
$L.Add('template <CommandType C> struct CmdPayload { using type = void; };  // default: command has no payload')
$n = 0
foreach($r in $rows){
  if($r.payload -eq 'void' -or $r.payload -eq ''){ continue }
  $L.Add(("template <> struct CmdPayload<CommandType::{0}> {{ using type = raw::{1}; }};" -f (San $r.command), (San $r.payload)))
  $n++
}
$L.Add('')
$L.Add('template <CommandType C> using CmdPayloadT = typename CmdPayload<C>::type;')
$L.Add('')
$L.Add('} // namespace op2::abi')
[IO.File]::WriteAllText((Join-Path $Out 'command_map.hpp'), ($L -join "`r`n") + "`r`n", (New-Object Text.UTF8Encoding($false)))
"command_map.hpp written: $n CommandType->payload specializations."
