<#
  gen-addresses.ps1 â€” re-reference/addresses.csv  ->  op2/abi/addresses.hpp
  Emits constexpr Outpost2.exe address constants, grouped by class into nested namespaces.
  Collisions (overloads at different addresses) get a numeric suffix; exact dups are dropped.
  Re-runnable.  Usage: powershell -File gen-addresses.ps1 [-Ref <dir>] [-Out <dir>]
#>
param([string]$Ref="$PSScriptRoot\..\..\re-reference", [string]$Out="$PSScriptRoot\..\include\op2\abi")
$ErrorActionPreference='Stop'
if(-not(Test-Path $Out)){ New-Item -ItemType Directory -Path $Out -Force | Out-Null }
function San([string]$s){ $s=[regex]::Replace($s,'[^A-Za-z0-9_]','_'); if($s -eq ''){ $s='_' }; if($s -match '^[0-9]'){ $s='_'+$s }; return $s }

$rows = Import-Csv -LiteralPath (Join-Path $Ref 'addresses.csv')
$L = New-Object System.Collections.Generic.List[string]
$L.Add('// AUTO-GENERATED by tools/gen-addresses.ps1 from re-reference/addresses.csv -- do not edit by hand.')
$L.Add('// Outpost2.exe addresses at preferred base 0x00400000 (relocated at runtime by op2/abi/memory.hpp).')
$L.Add('// Facts about Outpost2.exe (community reverse-engineering); see re-reference/RE-REFERENCE.md.')
$L.Add('#pragma once')
$L.Add('#include <cstdint>')
$L.Add('')
$L.Add('namespace op2::abi::addr {')
$L.Add('')

$total = 0
$groups = $rows | Group-Object class | Sort-Object Name
foreach($g in $groups){
  $cls = San $g.Name; if($cls -eq '_'){ $cls = 'Free' }
  $L.Add("namespace $cls {")
  $used = @{}
  $sorted = $g.Group | Sort-Object @{ e = { [Convert]::ToInt64($_.address.Substring(2),16) } }
  foreach($r in $sorted){
    $nm = San $r.symbol
    if($nm -eq '_'){ $nm = 'sub_' + $r.address.Substring(2) }
    $addr = $r.address
    $base = $nm; $i = 1
    while($used.ContainsKey($nm) -and $used[$nm] -ne $addr){ $i++; $nm = $base + '_' + $i }
    if($used.ContainsKey($nm)){ continue }    # same name + same address = duplicate binding
    $used[$nm] = $addr
    $cmt = $r.kind; if($r.detail){ $cmt = $cmt + ' ' + $r.detail }
    $L.Add(("  inline constexpr std::uintptr_t {0,-34} = {1};  // {2}" -f $nm, $addr, $cmt))
    $total++
  }
  $L.Add('}')
  $L.Add('')
}
$L.Add('} // namespace op2::abi::addr')
[IO.File]::WriteAllText((Join-Path $Out 'addresses.hpp'), ($L -join "`r`n") + "`r`n", (New-Object Text.UTF8Encoding($false)))
"addresses.hpp written: $total constants in $($groups.Count) class namespaces (from $($rows.Count) rows)."
