// AUTO-GENERATED by tools/gen-command-map.ps1 from re-reference/command-map.csv -- do not edit by hand.
// Maps abi::CommandType -> its command-packet payload struct (abi::raw::*).
#pragma once
#include "op2/abi/enums.hpp"        // CommandType
#include "op2/abi/raw/command.hpp"  // the raw::* payload structs this table names

namespace op2::abi {

template <CommandType C> struct CmdPayload { using type = void; };  // default: command has no payload
template <> struct CmdPayload<CommandType::Doze> { using type = raw::DozeCommand; };
template <> struct CmdPayload<CommandType::Move> { using type = raw::MoveCommand; };
template <> struct CmdPayload<CommandType::Dock> { using type = raw::MoveCommand; };
template <> struct CmdPayload<CommandType::DockEG> { using type = raw::MoveCommand; };
template <> struct CmdPayload<CommandType::Stop> { using type = raw::SimpleCommand; };
template <> struct CmdPayload<CommandType::Build> { using type = raw::BuildCommand; };
template <> struct CmdPayload<CommandType::BuildWall> { using type = raw::BuildWallCommand; };
template <> struct CmdPayload<CommandType::RemoveWall> { using type = raw::RemoveWallCommand; };
template <> struct CmdPayload<CommandType::Produce> { using type = raw::ProduceCommand; };
template <> struct CmdPayload<CommandType::TransferCargo> { using type = raw::TransferCargoCommand; };
template <> struct CmdPayload<CommandType::LoadCargo> { using type = raw::SingleUnitSimpleCommand; };
template <> struct CmdPayload<CommandType::UnloadCargo> { using type = raw::SingleUnitSimpleCommand; };
template <> struct CmdPayload<CommandType::Recycle> { using type = raw::RecycleCommand; };
template <> struct CmdPayload<CommandType::DumpCargo> { using type = raw::SingleUnitSimpleCommand; };
template <> struct CmdPayload<CommandType::Idle> { using type = raw::SingleUnitSimpleCommand; };
template <> struct CmdPayload<CommandType::Unidle> { using type = raw::SingleUnitSimpleCommand; };
template <> struct CmdPayload<CommandType::SelfDestruct> { using type = raw::SimpleCommand; };
template <> struct CmdPayload<CommandType::Scatter> { using type = raw::SimpleCommand; };
template <> struct CmdPayload<CommandType::Research> { using type = raw::ResearchCommand; };
template <> struct CmdPayload<CommandType::TrainScientists> { using type = raw::TrainScientistsCommand; };
template <> struct CmdPayload<CommandType::Transfer> { using type = raw::TransferCommand; };
template <> struct CmdPayload<CommandType::Launch> { using type = raw::LaunchCommand; };
template <> struct CmdPayload<CommandType::RepairObj> { using type = raw::RepairCommand; };
template <> struct CmdPayload<CommandType::Reprogram> { using type = raw::RepairCommand; };
template <> struct CmdPayload<CommandType::Dismantle> { using type = raw::RepairCommand; };
template <> struct CmdPayload<CommandType::Salvage> { using type = raw::SalvageCommand; };
template <> struct CmdPayload<CommandType::Create> { using type = raw::CreateCommand; };
template <> struct CmdPayload<CommandType::LightToggle> { using type = raw::LightToggleCommand; };
template <> struct CmdPayload<CommandType::Attack> { using type = raw::AttackCommand; };
template <> struct CmdPayload<CommandType::Guard> { using type = raw::AttackCommand; };
template <> struct CmdPayload<CommandType::StandGround> { using type = raw::MoveCommand; };
template <> struct CmdPayload<CommandType::CargoRoute> { using type = raw::CargoRouteCommand; };
template <> struct CmdPayload<CommandType::Patrol> { using type = raw::MoveCommand; };
template <> struct CmdPayload<CommandType::Poof> { using type = raw::SingleUnitSimpleCommand; };
template <> struct CmdPayload<CommandType::GameOpt> { using type = raw::GameOptCommand; };
template <> struct CmdPayload<CommandType::Chat> { using type = raw::ChatCommand; };
template <> struct CmdPayload<CommandType::Quit> { using type = raw::QuitCommand; };
template <> struct CmdPayload<CommandType::Ally> { using type = raw::AllyCommand; };
template <> struct CmdPayload<CommandType::MachineSettings> { using type = raw::MachineSettingsCommand; };

template <CommandType C> using CmdPayloadT = typename CmdPayload<C>::type;

} // namespace op2::abi
